/**
 * Application-level types.
 *
 * DB row types are generated by Prisma — import from '../../generated/prisma'.
 * This file retains only types NOT in the Prisma schema:
 * API response shapes, game logic types, and custom view types.
 */

// ─── Re-export Prisma enums & models ─────────────────────────
import type {
  GameMode as PrismaGameMode,
  QuestionType as PrismaQuestionType,
  Difficulty as PrismaDifficulty,
  League as PrismaLeague,
  FriendStatus as PrismaFriendStatus,
} from '../../generated/prisma';

export type GameMode = PrismaGameMode;
export type QuestionType = PrismaQuestionType;
export type Difficulty = PrismaDifficulty;
export type League = PrismaLeague;
export type FriendStatus = PrismaFriendStatus;

export type {
  User,
  GameSession,
  QuestionAnswer,
  SoQuestionCache,
  LeaderboardEntry as PrismaLeaderboardEntry,
  DailyChallenge,
  Friendship,
  Achievement,
  UserAchievement,
  DuelMatch,
  DuelQuestion,
} from '../../generated/prisma';

// ─── Stack Overflow API shapes ───────────────────────────────

export interface SoQuestion {
  question_id: number;
  title: string;
  body: string;             // HTML — strip before display
  body_markdown: string;    // Raw markdown (from custom SO filter)
  tags: string[];
  score: number;
  answer_count: number;
  accepted_answer_id: number | null;
  top_answer_body: string | null;   // HTML — strip before display
  top_answer_score: number | null;
  top_answer_author: string | null;
  view_count: number;
  difficulty: Difficulty;
  is_answered: boolean;
  creation_date: number;    // Unix timestamp
  owner_display_name?: string;
}

export interface SoAnswer {
  answer_id: number;
  question_id: number;
  score: number;
  is_accepted: boolean;
  body: string;
  body_markdown: string;
  owner: {
    display_name: string;
    reputation: number;
  };
}

// ─── Evaluation types ────────────────────────────────────────

export interface EvaluationResult {
  similarity: number;      // 0.0 – 1.0
  points: number;
  label: 'off' | 'partial' | 'good' | 'great' | 'excellent';
  feedback: string;
}

// ─── Game logic types ────────────────────────────────────────

export interface GameQuestion {
  question: SoQuestion;
  question_type: QuestionType;
  /** Display-ready question string (stripped HTML + title + excerpt) */
  question_text: string;
  /** The answer used for evaluation (for MCQ = tag, for fill = word, for string = top_answer_body) */
  correct_answer: string;
  options?: string[];         // MCQ: 4 shuffled choices
  blank_text?: string;        // fill_in_blank: title with ___ substituted
  hint?: string;              // Optional hint shown after wrong attempt
  time_limit: number;         // seconds
}

export interface SessionSnapshot {
  session_id: string;
  score: number;
  streak: number;
  streak_multiplier: number;
  questions_answered: number;
  correct_count: number;
  xp_earned: number;
}

export type ScoreRange = '0-10' | '10-100' | '100-500' | '500+';

// ─── Duel types ──────────────────────────────────────────────

export interface DuelState {
  match_id: string;
  status: 'waiting' | 'active' | 'completed' | 'cancelled';
  player1: DuelPlayerInfo;
  player2: DuelPlayerInfo | null;
  current_round: number;
  total_rounds: number;
  questions: DuelQuestionPayload[];
}

export interface DuelPlayerInfo {
  user_id: string;
  username: string;
  avatar_url: string | null;
  elo: number;
  score: number;
}

export interface DuelQuestionPayload {
  round_number: number;
  question: SoQuestion;
  question_type: QuestionType;
  options?: string[];
  blank_text?: string;
  time_limit: number;
  player1_answered: boolean;
  player2_answered: boolean;
}

export interface DuelResult {
  match_id: string;
  winner_id: string | null;
  player1: DuelPlayerResult;
  player2: DuelPlayerResult;
}

export interface DuelPlayerResult {
  user_id: string;
  username: string;
  score: number;
  correct_count: number;
  elo_change: number;
  new_elo: number;
}

// ─── Auth types ──────────────────────────────────────────────

export interface UserPayload {
  id: string;
  username: string;
  email: string;
  is_guest: boolean;
}

// ─── User profile (API response shape — matches UI) ──────────

export interface UserProfile {
  id: string;
  username: string;
  avatar_url: string | null;
  title: string | null;
  bio: string | null;
  elo: number;
  xp: number;
  level: number;
  league: League;
  total_duels: number;
  duels_won: number;
  win_rate: number;
  max_streak: number;
  current_streak: number;
  total_games: number;
  achievements_unlocked: number;
  achievements_total: number;
  rank: number;
  league_xp_current: number;
  league_xp_next: number;
  created_at: string;
}

export interface RecentMatch {
  match_id: string;
  opponent_username: string;
  opponent_avatar_url: string | null;
  result: 'win' | 'loss' | 'draw';
  elo_change: number;
  played_at: string;
}

// ─── Friend types ────────────────────────────────────────────

export interface FriendInfo {
  friendship_id: string;
  user_id: string;
  username: string;
  avatar_url: string | null;
  elo: number;
  league: League;
  last_active: string;
}

// ─── Achievement types ───────────────────────────────────────

export interface AchievementInfo {
  id: string;
  key: string;
  name: string;
  description: string;
  icon: string | null;
  color: string | null;
  unlocked: boolean;
  unlocked_at: string | null;
}

// ─── Leaderboard view type ───────────────────────────────────

export interface LeaderboardEntry {
  rank: number;
  username: string;
  score: number;
  mode: GameMode;
  tag: string | null;
  date: string;
}

export interface CategoryStats {
  tag: string;
  count: number;
  avg_score: number;
}
