/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as GameVsScreenRouteImport } from './routes/game.vs-screen'
import { Route as GameResultRouteImport } from './routes/game.result'
import { Route as GamePuzzleRouteImport } from './routes/game.puzzle'
import { Route as GameDuelRouteImport } from './routes/game.duel'
import { Route as GameDailyRouteImport } from './routes/game.daily'
import { Route as DashboardPuzzlesRouteImport } from './routes/dashboard.puzzles'
import { Route as DashboardLeaderboardRouteImport } from './routes/dashboard.leaderboard'
import { Route as DashboardFriendsRouteImport } from './routes/dashboard.friends'
import { Route as DashboardDuelsRouteImport } from './routes/dashboard.duels'
import { Route as DashboardUserIdRouteImport } from './routes/dashboard.user.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameVsScreenRoute = GameVsScreenRouteImport.update({
  id: '/game/vs-screen',
  path: '/game/vs-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const GameResultRoute = GameResultRouteImport.update({
  id: '/game/result',
  path: '/game/result',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePuzzleRoute = GamePuzzleRouteImport.update({
  id: '/game/puzzle',
  path: '/game/puzzle',
  getParentRoute: () => rootRouteImport,
} as any)
const GameDuelRoute = GameDuelRouteImport.update({
  id: '/game/duel',
  path: '/game/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const GameDailyRoute = GameDailyRouteImport.update({
  id: '/game/daily',
  path: '/game/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPuzzlesRoute = DashboardPuzzlesRouteImport.update({
  id: '/dashboard/puzzles',
  path: '/dashboard/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeaderboardRoute = DashboardLeaderboardRouteImport.update({
  id: '/dashboard/leaderboard',
  path: '/dashboard/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFriendsRoute = DashboardFriendsRouteImport.update({
  id: '/dashboard/friends',
  path: '/dashboard/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDuelsRoute = DashboardDuelsRouteImport.update({
  id: '/dashboard/duels',
  path: '/dashboard/duels',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserIdRoute = DashboardUserIdRouteImport.update({
  id: '/dashboard/user/$id',
  path: '/dashboard/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/duels': typeof DashboardDuelsRoute
  '/dashboard/friends': typeof DashboardFriendsRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/puzzles': typeof DashboardPuzzlesRoute
  '/game/daily': typeof GameDailyRoute
  '/game/duel': typeof GameDuelRoute
  '/game/puzzle': typeof GamePuzzleRoute
  '/game/result': typeof GameResultRoute
  '/game/vs-screen': typeof GameVsScreenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/user/$id': typeof DashboardUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/duels': typeof DashboardDuelsRoute
  '/dashboard/friends': typeof DashboardFriendsRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/puzzles': typeof DashboardPuzzlesRoute
  '/game/daily': typeof GameDailyRoute
  '/game/duel': typeof GameDuelRoute
  '/game/puzzle': typeof GamePuzzleRoute
  '/game/result': typeof GameResultRoute
  '/game/vs-screen': typeof GameVsScreenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/user/$id': typeof DashboardUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/duels': typeof DashboardDuelsRoute
  '/dashboard/friends': typeof DashboardFriendsRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/puzzles': typeof DashboardPuzzlesRoute
  '/game/daily': typeof GameDailyRoute
  '/game/duel': typeof GameDuelRoute
  '/game/puzzle': typeof GamePuzzleRoute
  '/game/result': typeof GameResultRoute
  '/game/vs-screen': typeof GameVsScreenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/user/$id': typeof DashboardUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard/duels'
    | '/dashboard/friends'
    | '/dashboard/leaderboard'
    | '/dashboard/puzzles'
    | '/game/daily'
    | '/game/duel'
    | '/game/puzzle'
    | '/game/result'
    | '/game/vs-screen'
    | '/dashboard/'
    | '/dashboard/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard/duels'
    | '/dashboard/friends'
    | '/dashboard/leaderboard'
    | '/dashboard/puzzles'
    | '/game/daily'
    | '/game/duel'
    | '/game/puzzle'
    | '/game/result'
    | '/game/vs-screen'
    | '/dashboard'
    | '/dashboard/user/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard/duels'
    | '/dashboard/friends'
    | '/dashboard/leaderboard'
    | '/dashboard/puzzles'
    | '/game/daily'
    | '/game/duel'
    | '/game/puzzle'
    | '/game/result'
    | '/game/vs-screen'
    | '/dashboard/'
    | '/dashboard/user/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  DashboardDuelsRoute: typeof DashboardDuelsRoute
  DashboardFriendsRoute: typeof DashboardFriendsRoute
  DashboardLeaderboardRoute: typeof DashboardLeaderboardRoute
  DashboardPuzzlesRoute: typeof DashboardPuzzlesRoute
  GameDailyRoute: typeof GameDailyRoute
  GameDuelRoute: typeof GameDuelRoute
  GamePuzzleRoute: typeof GamePuzzleRoute
  GameResultRoute: typeof GameResultRoute
  GameVsScreenRoute: typeof GameVsScreenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUserIdRoute: typeof DashboardUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/vs-screen': {
      id: '/game/vs-screen'
      path: '/game/vs-screen'
      fullPath: '/game/vs-screen'
      preLoaderRoute: typeof GameVsScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/result': {
      id: '/game/result'
      path: '/game/result'
      fullPath: '/game/result'
      preLoaderRoute: typeof GameResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/puzzle': {
      id: '/game/puzzle'
      path: '/game/puzzle'
      fullPath: '/game/puzzle'
      preLoaderRoute: typeof GamePuzzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/duel': {
      id: '/game/duel'
      path: '/game/duel'
      fullPath: '/game/duel'
      preLoaderRoute: typeof GameDuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/daily': {
      id: '/game/daily'
      path: '/game/daily'
      fullPath: '/game/daily'
      preLoaderRoute: typeof GameDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/puzzles': {
      id: '/dashboard/puzzles'
      path: '/dashboard/puzzles'
      fullPath: '/dashboard/puzzles'
      preLoaderRoute: typeof DashboardPuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leaderboard': {
      id: '/dashboard/leaderboard'
      path: '/dashboard/leaderboard'
      fullPath: '/dashboard/leaderboard'
      preLoaderRoute: typeof DashboardLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/friends': {
      id: '/dashboard/friends'
      path: '/dashboard/friends'
      fullPath: '/dashboard/friends'
      preLoaderRoute: typeof DashboardFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/duels': {
      id: '/dashboard/duels'
      path: '/dashboard/duels'
      fullPath: '/dashboard/duels'
      preLoaderRoute: typeof DashboardDuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user/$id': {
      id: '/dashboard/user/$id'
      path: '/dashboard/user/$id'
      fullPath: '/dashboard/user/$id'
      preLoaderRoute: typeof DashboardUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  DashboardDuelsRoute: DashboardDuelsRoute,
  DashboardFriendsRoute: DashboardFriendsRoute,
  DashboardLeaderboardRoute: DashboardLeaderboardRoute,
  DashboardPuzzlesRoute: DashboardPuzzlesRoute,
  GameDailyRoute: GameDailyRoute,
  GameDuelRoute: GameDuelRoute,
  GamePuzzleRoute: GamePuzzleRoute,
  GameResultRoute: GameResultRoute,
  GameVsScreenRoute: GameVsScreenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUserIdRoute: DashboardUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
